name: FunPay AutoRaise

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  autoraise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download FunPayAPI
        run: |
          git clone --depth 1 https://github.com/MorikTV/FunPayAPI.git
          pip install requests beautifulsoup4 lxml requests-toolbelt

      - name: Run AutoRaise
        env:
          FUNPAY_GOLDEN_KEY: ${{ secrets.FUNPAY_GOLDEN_KEY }}
        run: |
          python main.py
